import re

# Known franchise brand names, all lowercase.
# Grouped by the four target business categories plus general chains.
# Matching is prefix-based: a result is a franchise if its name starts with
# one of these brands (case-insensitive) followed by a word boundary character
# (space, #, comma, dash, slash) or end of string.
KNOWN_FRANCHISES: frozenset[str] = frozenset({
    # ── Local Trades ──────────────────────────────────────────────────────────
    "mr. rooter",
    "mr rooter",
    "roto-rooter",
    "roto rooter",
    "mr. electric",
    "mr electric",
    "mr. appliance",
    "mr appliance",
    "mr. handyman",
    "mr handyman",
    "neighborly",
    "molly maid",
    "merry maids",
    "maidpro",
    "maid brigade",
    "jan-pro",
    "jan pro",
    "jani-king",
    "jani king",
    "coverall",
    "servicemaster",
    "servpro",
    "stanley steemer",
    "1-800-got-junk",
    "1800 got junk",
    "bin there dump that",
    "college hunks hauling junk",
    "college hunks",
    "two men and a truck",
    "terminix",
    "orkin",
    "rentokil",
    "truly nolen",
    "trugreen",
    "lawn doctor",
    "spring-green lawn care",
    "spring green lawn care",
    "weed man",
    "five star painting",
    "certapro painters",
    "sherwin-williams",
    "sherwin williams",
    "benjamin moore",
    "jiffy lube",
    "midas",
    "meineke",
    "monro",
    "pep boys",
    "firestone complete auto care",
    "firestone",
    "goodyear auto service",
    "goodyear tire",
    "valvoline",
    "christian brothers automotive",
    "car-x",
    "aamco",
    "cottman transmission",
    "big o tires",
    "maaco",
    "abra auto body",

    # ── Professional Services ─────────────────────────────────────────────────
    "h&r block",
    "hr block",
    "liberty tax",
    "jackson hewitt",
    "edward jones",
    "ameriprise financial",
    "northwestern mutual",
    "new york life",
    "re/max",
    "remax",
    "keller williams",
    "century 21",
    "century21",
    "coldwell banker",
    "era real estate",
    "berkshire hathaway homeservices",
    "sotheby's international realty",
    "sothebys international realty",
    "exp realty",
    "better homes and gardens real estate",
    "howard hanna",
    "weichert realtors",
    "long & foster",
    "state farm",
    "allstate",
    "farmers insurance",
    "nationwide",
    "american family insurance",
    "country financial",

    # ── Medical / Healthcare ──────────────────────────────────────────────────
    "aspen dental",
    "bright now dental",
    "gentle dental",
    "western dental",
    "pacific dental",
    "smile brands",
    "smile doctors",
    "heartland dental",
    "clearchoice",
    "clear choice",
    "the joint chiropractic",
    "the joint",
    "joint chiropractic",
    "massage envy",
    "hand & stone",
    "hand and stone",
    "elements massage",
    "citymd",
    "concentra",
    "gohealth urgent care",
    "afc urgent care",
    "american family care",
    "fastmed urgent care",
    "nextcare urgent care",
    "nextcare",
    "medexpress",
    "carenow",
    "wellnow urgent care",
    "premier urgent care",
    "davita",
    "fresenius kidney care",
    "lenscrafters",
    "pearle vision",
    "for eyes",
    "national vision",
    "myeyedr",
    "america's best contacts",
    "americas best contacts",
    "visionworks",
    "eyeglass world",
    "beltone",
    "miracle-ear",
    "miracle ear",

    # ── Niche Retail ──────────────────────────────────────────────────────────
    "bath & body works",
    "bath and body works",
    "victoria's secret",
    "victoria secret",
    "american eagle outfitters",
    "american eagle",
    "hollister",
    "abercrombie & fitch",
    "abercrombie",
    "h&m",
    "zara",
    "forever 21",
    "express",
    "lane bryant",
    "torrid",
    "cato",
    "tj maxx",
    "t.j. maxx",
    "marshalls",
    "ross",
    "burlington coat factory",
    "burlington",
    "old navy",
    "gap",
    "banana republic",
    "j.crew",
    "j crew",
    "ann taylor",
    "loft",
    "foot locker",
    "famous footwear",
    "dsw",
    "shoe carnival",
    "finish line",
    "journeys",
    "rack room shoes",
    "kay jewelers",
    "kay",
    "zales",
    "jared",
    "pandora",
    "helzberg diamonds",
    "books-a-million",
    "books a million",
    "half price books",
    "hallmark gold crown",
    "hallmark",
    "spencer gifts",
    "spencers",
    "things remembered",
    "kirklands",
    "kirkland's",
    "petco",
    "petsmart",
    "petsense",
    "pet supplies plus",
    "ashley homestore",
    "ashley furniture",
    "rooms to go",
    "pier 1",
    "pier one",
    "tuesday morning",
    "at home",
    "big lots",
    "ollie's bargain outlet",
    "ollies bargain outlet",
    "five below",
    "dollar tree",
    "dollar general",
    "family dollar",
    "ace hardware",
    "true value",
    "the ups store",
    "ups store",
    "fedex office",
    "batteries plus bulbs",
    "batteries plus",
    "7-eleven",
    "7 eleven",
    "circle k",

    # ── Hair / Beauty ─────────────────────────────────────────────────────────
    "great clips",
    "sport clips",
    "supercuts",
    "cost cutters",
    "hair cuttery",
    "fantastic sams",
    "fantastic sam's",
    "floyd's barbershop",
    "roosters men's grooming",
    "roosters",
    "first choice haircutters",
    "smartstyle",
    "regis salon",
    "regis",
    "mastercuts",
    "ulta beauty",
    "ulta",
    "european wax center",
    "the wax center",

    # ── Fitness ───────────────────────────────────────────────────────────────
    "planet fitness",
    "anytime fitness",
    "gold's gym",
    "golds gym",
    "la fitness",
    "24 hour fitness",
    "crunch fitness",
    "crunch gym",
    "snap fitness",
    "curves",
    "orangetheory",
    "orangetheory fitness",
    "f45 training",
    "f45",
    "pure barre",
    "club pilates",
    "cyclebar",
    "9round",
    "title boxing club",
    "retro fitness",
    "youfit",

    # ── Food / Coffee (catch common ones that slip through) ───────────────────
    "mcdonald's",
    "mcdonalds",
    "subway",
    "burger king",
    "wendy's",
    "wendys",
    "taco bell",
    "kfc",
    "chick-fil-a",
    "chick fil a",
    "popeyes",
    "popeye's",
    "sonic",
    "dairy queen",
    "jack in the box",
    "carl's jr",
    "hardee's",
    "arby's",
    "five guys",
    "shake shack",
    "whataburger",
    "white castle",
    "starbucks",
    "dunkin'",
    "dunkin",
    "tim hortons",
    "panera bread",
    "panera",
    "domino's",
    "dominoes",
    "pizza hut",
    "papa john's",
    "papa johns",
    "little caesars",
    "chipotle",
    "panda express",
    "jimmy john's",
    "jimmy johns",
    "jersey mike's",
    "jersey mikes",
    "firehouse subs",
    "wingstop",
    "buffalo wild wings",
    "applebee's",
    "applebees",
    "chili's",
    "chilis",
    "t.g.i. friday's",
    "tgi fridays",
    "red lobster",
    "outback steakhouse",
    "texas roadhouse",
    "olive garden",
    "cracker barrel",
    "ihop",
    "denny's",
    "dennys",
    "waffle house",
})

# Compiled once at import time for fast matching.
# Sorts longest brands first to avoid a shorter prefix shadowing a longer one.
_FRANCHISE_RE = re.compile(
    r"^(?:" + "|".join(re.escape(b) for b in sorted(KNOWN_FRANCHISES, key=len, reverse=True)) + r")(?:[\s#,/'\\-]|$)",
    re.IGNORECASE,
)

# Franchise location-number pattern: "Subway #1234", "Great Clips #42"
_LOCATION_NUM_RE = re.compile(r"\s#\d+")


def is_franchise(name: str) -> bool:
    if _LOCATION_NUM_RE.search(name):
        return True
    return bool(_FRANCHISE_RE.match(name.strip()))


def filter_franchises(businesses: list[dict]) -> list[dict]:
    return [b for b in businesses if not is_franchise(b["name"])]
